# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/A_GW/Courses/Computer_organization/lab/vivado/CPU/CPU.cache/wt [current_project]
set_property parent.project_path D:/A_GW/Courses/Computer_organization/lab/vivado/CPU/CPU.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_ip d:/A_GW/Courses/Computer_organization/lab/vivado/CPU/CPU.srcs/sources_1/ip/Ins_Rom/Ins_Rom.xci
set_property is_locked true [get_files d:/A_GW/Courses/Computer_organization/lab/vivado/CPU/CPU.srcs/sources_1/ip/Ins_Rom/Ins_Rom.xci]

synth_design -top Ins_Rom -part xc7a35tcpg236-1 -mode out_of_context
rename_ref -prefix_all Ins_Rom_
write_checkpoint -noxdef Ins_Rom.dcp
catch { report_utilization -file Ins_Rom_utilization_synth.rpt -pb Ins_Rom_utilization_synth.pb }
if { [catch {
  file copy -force D:/A_GW/Courses/Computer_organization/lab/vivado/CPU/CPU.runs/Ins_Rom_synth_1/Ins_Rom.dcp d:/A_GW/Courses/Computer_organization/lab/vivado/CPU/CPU.srcs/sources_1/ip/Ins_Rom/Ins_Rom.dcp
} _RESULT ] } { 
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}
if { [catch {
  write_verilog -force -mode synth_stub d:/A_GW/Courses/Computer_organization/lab/vivado/CPU/CPU.srcs/sources_1/ip/Ins_Rom/Ins_Rom_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode synth_stub d:/A_GW/Courses/Computer_organization/lab/vivado/CPU/CPU.srcs/sources_1/ip/Ins_Rom/Ins_Rom_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_verilog -force -mode funcsim d:/A_GW/Courses/Computer_organization/lab/vivado/CPU/CPU.srcs/sources_1/ip/Ins_Rom/Ins_Rom_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode funcsim d:/A_GW/Courses/Computer_organization/lab/vivado/CPU/CPU.srcs/sources_1/ip/Ins_Rom/Ins_Rom_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if {[file isdir D:/A_GW/Courses/Computer_organization/lab/vivado/CPU/CPU.ip_user_files/ip/Ins_Rom]} {
  catch { 
    file copy -force d:/A_GW/Courses/Computer_organization/lab/vivado/CPU/CPU.srcs/sources_1/ip/Ins_Rom/Ins_Rom_stub.v D:/A_GW/Courses/Computer_organization/lab/vivado/CPU/CPU.ip_user_files/ip/Ins_Rom
  }
}

if {[file isdir D:/A_GW/Courses/Computer_organization/lab/vivado/CPU/CPU.ip_user_files/ip/Ins_Rom]} {
  catch { 
    file copy -force d:/A_GW/Courses/Computer_organization/lab/vivado/CPU/CPU.srcs/sources_1/ip/Ins_Rom/Ins_Rom_stub.vhdl D:/A_GW/Courses/Computer_organization/lab/vivado/CPU/CPU.ip_user_files/ip/Ins_Rom
  }
}
