# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/A_GW/Courses/Computer_organization/lab/vivado/18340045_guanyawen/18340045_guanyawen_project_files/CPU/CPU.cache/wt [current_project]
set_property parent.project_path D:/A_GW/Courses/Computer_organization/lab/vivado/18340045_guanyawen/18340045_guanyawen_project_files/CPU/CPU.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
add_files D:/A_GW/Courses/Computer_organization/lab/vivado/18340045_guanyawen/18340045_guanyawen_project_files/CPU/IMemInput.coe
read_verilog -library xil_defaultlib {
  D:/A_GW/Courses/Computer_organization/lab/vivado/18340045_guanyawen/18340045_guanyawen_project_files/CPU/CPU.srcs/sources_1/new/display.v
  D:/A_GW/Courses/Computer_organization/lab/vivado/18340045_guanyawen/18340045_guanyawen_project_files/CPU/CPU.srcs/sources_1/new/regFile.v
  D:/A_GW/Courses/Computer_organization/lab/vivado/18340045_guanyawen/18340045_guanyawen_project_files/CPU/CPU.srcs/sources_1/new/controller.v
  D:/A_GW/Courses/Computer_organization/lab/vivado/18340045_guanyawen/18340045_guanyawen_project_files/CPU/CPU.srcs/sources_1/new/signext.v
  D:/A_GW/Courses/Computer_organization/lab/vivado/18340045_guanyawen/18340045_guanyawen_project_files/CPU/CPU.srcs/sources_1/new/IMEM.v
  D:/A_GW/Courses/Computer_organization/lab/vivado/18340045_guanyawen/18340045_guanyawen_project_files/CPU/CPU.srcs/sources_1/new/DRAM.v
  D:/A_GW/Courses/Computer_organization/lab/vivado/18340045_guanyawen/18340045_guanyawen_project_files/CPU/CPU.srcs/sources_1/new/aluCtr.v
  D:/A_GW/Courses/Computer_organization/lab/vivado/18340045_guanyawen/18340045_guanyawen_project_files/CPU/CPU.srcs/sources_1/new/ALU.v
  D:/A_GW/Courses/Computer_organization/lab/vivado/18340045_guanyawen/18340045_guanyawen_project_files/CPU/CPU.srcs/sources_1/new/top.v
}
read_xdc D:/A_GW/Courses/Computer_organization/lab/vivado/18340045_guanyawen/18340045_guanyawen_project_files/CPU/CPU.srcs/constrs_1/new/display_pin.xdc
set_property used_in_implementation false [get_files D:/A_GW/Courses/Computer_organization/lab/vivado/18340045_guanyawen/18340045_guanyawen_project_files/CPU/CPU.srcs/constrs_1/new/display_pin.xdc]

synth_design -top top -part xc7a35tcpg236-1
write_checkpoint -noxdef top.dcp
catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
